// Bibliothèque des styles disponibles sur le site.
// Pour ajouter un style : génère son .stp.json (voir scripts/generate-stp.mjs),
// dépose-le dans /stp/, puis ajoute une entrée ici.
const STYLES = [
  {
    id: "executive-studio",
    label: "Executive Studio",
    description: "Fond sombre, lumière douce, rendu corporate haut de gamme.",
    stpFile: "stp/executive-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/executive-studio-after.jpg",
  },
  {
    id: "corporate-studio",
    label: "Corporate",
    description: "Fond gris clair uni, lumière douce, rendu institutionnel.",
    stpFile: "stp/corporate-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/corporate-studio-after.jpg",
  },
  {
    id: "linkedin-studio",
    label: "LinkedIn",
    description: "Bureau flouté, lumière naturelle, ton pro et accessible.",
    stpFile: "stp/linkedin-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/linkedin-studio-after.jpg",
  },
  {
    id: "startup-studio",
    label: "Startup",
    description: "Fond flouté façon loft, lumière naturelle, ambiance moderne.",
    stpFile: "stp/startup-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/startup-studio-after.jpg",
  },
  {
    id: "editorial-studio",
    label: "Editorial",
    description: "Lumière dramatique, fort contraste, rendu magazine.",
    stpFile: "stp/editorial-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/editorial-studio-after.jpg",
  },
  {
    id: "dark-studio",
    label: "Dark Studio",
    description: "Fond noir profond, lumière dure, ambiance intense.",
    stpFile: "stp/dark-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/dark-studio-after.jpg",
  },
  {
    id: "cinematic-studio",
    label: "Cinematic",
    description: "Étalonnage teal-orange, faible profondeur de champ, grain film.",
    stpFile: "stp/cinematic-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/cinematic-studio-after.jpg",
  },
  {
    id: "black-and-white-studio",
    label: "Black & White",
    description: "Noir et blanc classique, fort contraste, intemporel.",
    stpFile: "stp/black-and-white-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/black-and-white-studio-after.jpg",
  },
  {
    id: "consulting-studio",
    label: "Consulting",
    description: "Bureau vitré flouté, ton froid et net, très épuré.",
    stpFile: "stp/consulting-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/consulting-studio-after.jpg",
  },
  {
    id: "warm-portrait-studio",
    label: "Portrait chaleureux",
    description: "Tons ambrés, lumière dorée enveloppante, chaleureux.",
    stpFile: "stp/warm-portrait-studio.stp.json",
    beforeImage: "assets/styles/all-studio-before.jpg",
    afterImage: "assets/styles/warm-portrait-studio-after.jpg",
  },
];
